config/routes.rb
Rails.application.routes.draw do
  resources :hashtags
  resources :colleges do
  collection {post :import}
  end
  root to: "colleges#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
  require 'csv'
  def self.import(file)
    CSV.foreach(file.path, headers:true) do |row|
      College.create! row.to_hash
    end
  end
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  belongs_to :College
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all
  end
  def import
    College.import(params[:file])
    redirect_to root_url, notice: "It worked!"
  end
  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully created.' }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to @college, notice: 'College was successfully updated.' }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'College was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_params
      params.require(:college).permit(:name, :private)
    end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  before_action :set_hashtag, only: [:show, :edit, :update, :destroy]

  # GET /hashtags
  # GET /hashtags.json
  def index
    @hashtags = Hashtag.all
  end

  # GET /hashtags/1
  # GET /hashtags/1.json
  def show
  end

  # GET /hashtags/new
  def new
    @hashtag = Hashtag.new
  end

  # GET /hashtags/1/edit
  def edit
  end

  # POST /hashtags
  # POST /hashtags.json
  def create
    @hashtag = Hashtag.new(hashtag_params)

    respond_to do |format|
      if @hashtag.save
        format.html { redirect_to @hashtag, notice: 'Hashtag was successfully created.' }
        format.json { render :show, status: :created, location: @hashtag }
      else
        format.html { render :new }
        format.json { render json: @hashtag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hashtags/1
  # PATCH/PUT /hashtags/1.json
  def update
    respond_to do |format|
      if @hashtag.update(hashtag_params)
        format.html { redirect_to @hashtag, notice: 'Hashtag was successfully updated.' }
        format.json { render :show, status: :ok, location: @hashtag }
      else
        format.html { render :edit }
        format.json { render json: @hashtag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hashtags/1
  # DELETE /hashtags/1.json
  def destroy
    @hashtag.destroy
    respond_to do |format|
      format.html { redirect_to hashtags_url, notice: 'Hashtag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hashtag
      @hashtag = Hashtag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hashtag_params
      params.require(:hashtag).permit(:name, :College_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/views/colleges/_form.html.erb
<%= form_with(model: college, local: true) do |form| %>
  <% if college.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
      <% college.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :college_name %>
  </div>

  <div class="field">
    <%= form.label :private %>
    <%= form.check_box :private, id: :college_private %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/colleges/edit.html.erb
<h1>Editing College</h1>

<%= render 'form', college: @college %>

<%= link_to 'Show', @college %> |
<%= link_to 'Back', colleges_path %>

app/views/colleges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Colleges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Private</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colleges.each do |college| %>
      <tr>
        <td><%= college.name %></td>
        <td><%= college.private %></td>
        <td><%= link_to 'Show', college %></td>
        <td><%= link_to 'Edit', edit_college_path(college) %></td>
        <td><%= link_to 'Destroy', college, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h4>Import</h4>
  <%= form_tag import_colleges_path, multipart: true do %>
    <%=file_field_tag :file %>
    <%=submit_tag "import csv" %>
  <%end%>
<br>

<%= link_to 'New College', new_college_path %>

app/views/colleges/new.html.erb
<h1>New College</h1>

<%= render 'form', college: @college %>

<%= link_to 'Back', colleges_path %>

app/views/colleges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @college.name %>
</p>

<p>
  <strong>Private:</strong>
  <%= @college.private %>
</p>

<%= link_to 'Edit', edit_college_path(@college) %> |
<%= link_to 'Back', colleges_path %>

app/views/hashtags/_form.html.erb
<%= form_with(model: hashtag, local: true) do |form| %>
  <% if hashtag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hashtag.errors.count, "error") %> prohibited this hashtag from being saved:</h2>

      <ul>
      <% hashtag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :hashtag_name %>
  </div>

  <div class="field">
    <%= form.label :College_id %>
    <%= form.text_field :College_id, id: :hashtag_College_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hashtags/edit.html.erb
<h1>Editing Hashtag</h1>

<%= render 'form', hashtag: @hashtag %>

<%= link_to 'Show', @hashtag %> |
<%= link_to 'Back', hashtags_path %>

app/views/hashtags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hashtags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>College</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hashtags.each do |hashtag| %>
      <tr>
        <td><%= hashtag.name %></td>
        <td><%= hashtag.College %></td>
        <td><%= link_to 'Show', hashtag %></td>
        <td><%= link_to 'Edit', edit_hashtag_path(hashtag) %></td>
        <td><%= link_to 'Destroy', hashtag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hashtag', new_hashtag_path %>

app/views/hashtags/new.html.erb
<h1>New Hashtag</h1>

<%= render 'form', hashtag: @hashtag %>

<%= link_to 'Back', hashtags_path %>

app/views/hashtags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hashtag.name %>
</p>

<p>
  <strong>College:</strong>
  <%= @hashtag.College %>
</p>

<%= link_to 'Edit', edit_hashtag_path(@hashtag) %> |
<%= link_to 'Back', hashtags_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SentientColleges</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>